/// Rozet detayında «Nasıl kazanılır?» (`badge_how_title`) ve tüm `badge_ht_*` metinleri.
/// `tr` / `en` tam seti `app_localizations.dart` içinde; diğer 16 dil burada.
/// `badge_ht_lang_*` dil kaşifi rozetleri — ana haritalarda zaten tanımlı, burada yok.
String? badgeHowToString(String languageCode, String key) {
  final lc = languageCode.toLowerCase();
  if (lc == 'tr' || lc == 'en') return null;
  final m = _badgeHowToByLang[lc];
  if (m == null) return null;
  return m[key];
}

const Map<String, Map<String, String>> _badgeHowToByLang = {
  'de': _deHowTo,
  'es': _esHowTo,
  'fr': _frHowTo,
  'ar': _arHowTo,
  'fa': _faHowTo,
  'zh': _zhHowTo,
  'id': _idHowTo,
  'ku': _kuHowTo,
  'ru': _ruHowTo,
  'ja': _jaHowTo,
  'ko': _koHowTo,
  'hi': _hiHowTo,
  'ur': _urHowTo,
  'pt': _ptHowTo,
  'it': _itHowTo,
  'pl': _plHowTo,
};

const Map<String, String> _deHowTo = {
  'badge_how_title': 'So verdienst du es',
  'badge_ht_first_game': 'Beende vom Startbildschirm eine Runde in Schnell-Mathe, Themen (Lernpfad), Richtig/Falsch oder Boss-Kampf bis zum Ergebnisbildschirm.',
  'badge_ht_games_10': 'Jede abgeschlossene Sitzung zählt einmal. Spiele regelmäßig Schnell-Mathe, Themen, Richtig/Falsch oder Boss.',
  'badge_ht_games_50': 'Spiele weiter; die Summe wächst über alle Modi.',
  'badge_ht_games_100': 'Themenpraxis und kurze Sessions erhöhen die Zahl mit der Zeit.',
  'badge_ht_games_500': 'Langfristig: Schnell-Mathe, Themen und Boss mischen.',
  'badge_ht_questions_100': 'Jede beantwortete Frage zählt (richtig oder falsch). Löse Fragen in Schnell-Mathe und Themen.',
  'badge_ht_questions_500': 'Lernpfad und Themenseiten liefern viele Fragen pro Session.',
  'badge_ht_questions_1000': 'Kombiniere Tagesaufgaben mit regelmäßiger Übung.',
  'badge_ht_questions_5000': 'Sehr langfristig: über Altersstufen und Themen hinweg spielen.',
  'badge_ht_streak_5': 'In einer Sitzung mehrere richtige Antworten hintereinander ohne dazwischenliegende Falsche.',
  'badge_ht_streak_10': 'Konzentration; richtige Treffer im Boss zählen auch zur Serie.',
  'badge_ht_streak_25': 'Schwere Themen brauchen ruhiges Tempo für die Serie.',
  'badge_ht_streak_50': 'Leichter starten, Schwierigkeit steigern, wenn Serien stabil sind.',
  'badge_ht_streak_100': 'Beste Serie = längste Kette richtiger Antworten in einer Sitzung.',
  'badge_ht_fast_10': 'Pro Frage werden Sekunden gezählt. 6–10 s = schnell; ≤5 s = superschnell (Themen & Schnell-Mathe).',
  'badge_ht_fast_50': 'Frage schnell lesen und antworten, sobald du sicher bist.',
  'badge_ht_fast_200': 'Viele schnelle richtige Antworten über Sessions summieren sich.',
  'badge_ht_superfast_10': 'Ziele auf Antworten innerhalb von 5 Sekunden, wenn der Timer es erlaubt.',
  'badge_ht_perfect_1': 'Beende eine Sitzung ohne falsche Antworten und mit mindestens einer beantworteten Frage.',
  'badge_ht_perfect_5': 'Wiederhole perfekte Sitzungen (keine falschen Antworten in diesem Lauf).',
  'badge_ht_perfect_20': 'Perfekt = keine falschen Antworten bis Sitzungsende (Leben können in manchen Modi anders verloren gehen).',
  'badge_ht_perfect_50': 'Perfekte Spiele sammeln sich langsam; leichtere Einstellungen helfen beim Üben.',
  'badge_ht_first_friend': 'Unter Freunde jemanden hinzufügen oder eine Einladung annehmen.',
  'badge_ht_friends_5': 'Mehr Freunde in der App hinzufügen, um diese Zahl zu erhöhen.',
  'badge_ht_friends_20': 'Mit Klassenkameraden oder Familienkontos verbinden.',
  'badge_ht_days_7': 'An aufeinanderfolgenden Kalendertagen je mindestens eine abgeschlossene Spielsitzung; am selben Tag zählt extra nur einmal.',
  'badge_ht_days_30': 'Kurze tägliche Sessions halten den Kalender-Streak.',
  'badge_ht_days_100': 'Sehr langfristiges Treue-Abzeichen.',
  'badge_ht_score_1000': 'Punkte aus Sitzungen (richtige Antworten usw.) addieren sich zur Gesamtpunktzahl.',
  'badge_ht_score_10000': 'Themen, Boss und Schnell-Mathe-Punkte kombinieren.',
  'badge_ht_score_100000': 'Ziele auf hohe Punktzahlen in allen Modi.',
};

const Map<String, String> _esHowTo = {
  'badge_how_title': 'Cómo conseguirlo',
  'badge_ht_first_game': 'Desde inicio, termina una partida en Matemáticas rápidas, Temas (ruta), Verdadero/Falso o Jefe hasta la pantalla de resultados.',
  'badge_ht_games_10': 'Cada sesión completada cuenta una vez. Juega con regularidad esos modos.',
  'badge_ht_games_50': 'Sigue terminando partidas; el total suma en todos los modos.',
  'badge_ht_games_100': 'Práctica por temas y sesiones cortas aumentan el contador con el tiempo.',
  'badge_ht_games_500': 'Meta larga: combina rápidas, temas y jefe.',
  'badge_ht_questions_100': 'Cada pregunta respondida cuenta (acierto o fallo). Resuelve en rápidas y por temas.',
  'badge_ht_questions_500': 'La ruta de aprendizaje y temas dan muchas preguntas por sesión.',
  'badge_ht_questions_1000': 'Combina tareas diarias con práctica regular.',
  'badge_ht_questions_5000': 'Muy largo plazo: juega en distintas edades y temas.',
  'badge_ht_streak_5': 'En una sesión, varias correctas seguidas sin error entre medias.',
  'badge_ht_streak_10': 'Mantén foco; aciertos en jefe también alargan la racha.',
  'badge_ht_streak_25': 'Temas difíciles requieren ritmo tranquilo para la racha.',
  'badge_ht_streak_50': 'Empieza fácil y sube dificultad cuando la racha sea estable.',
  'badge_ht_streak_100': 'Mejor racha = cadena más larga de aciertos en una sola sesión.',
  'badge_ht_fast_10': 'Por pregunta se miden segundos. 6–10 s = rápida; ≤5 s = superrápida (temas y rápidas).',
  'badge_ht_fast_50': 'Lee rápido y responde en cuanto estés seguro.',
  'badge_ht_fast_200': 'Muchas respuestas rápidas correctas suman entre sesiones.',
  'badge_ht_superfast_10': 'Intenta responder en ≤5 s cuando el temporizador lo permita.',
  'badge_ht_perfect_1': 'Termina una sesión sin fallos y con al menos una pregunta respondida.',
  'badge_ht_perfect_5': 'Repite sesiones perfectas (sin fallos en esa partida).',
  'badge_ht_perfect_20': 'Perfecto = sin fallos hasta el final (en algunos modos las vidas pueden cambiar de otra forma).',
  'badge_ht_perfect_50': 'Las partidas perfectas cogen tiempo; ajustes más fáciles ayudan.',
  'badge_ht_first_friend': 'En Amigos añade a alguien o acepta una invitación.',
  'badge_ht_friends_5': 'Añade más amigos en la app para subir esta estadística.',
  'badge_ht_friends_20': 'Conecta con compañeros o cuentas familiares.',
  'badge_ht_days_7': 'Al menos una sesión terminada en días de calendario seguidos; el mismo día extra cuenta como un día.',
  'badge_ht_days_30': 'Sesiones cortas diarias mantienen la racha del calendario.',
  'badge_ht_days_100': 'Insignia de lealtad a muy largo plazo.',
  'badge_ht_score_1000': 'Los puntos de sesiones (aciertos, etc.) suman a tu puntuación total.',
  'badge_ht_score_10000': 'Combina puntos de temas, jefe y matemáticas rápidas.',
  'badge_ht_score_100000': 'Busca partidas con muchos puntos en todos los modos.',
};

const Map<String, String> _frHowTo = {
  'badge_how_title': 'Comment le gagner',
  'badge_ht_first_game': 'Depuis l’accueil, termine une session Maths rapide, Thèmes (parcours), Vrai/Faux ou Boss jusqu’à l’écran de résultats.',
  'badge_ht_games_10': 'Chaque session terminée compte une fois. Joue régulièrement à ces modes.',
  'badge_ht_games_50': 'Continue à finir des parties ; le total s’additionne sur tous les modes.',
  'badge_ht_games_100': 'La pratique par thème et les sessions courtes font monter le compteur.',
  'badge_ht_games_500': 'Objectif long terme : alterner rapide, thèmes et boss.',
  'badge_ht_questions_100': 'Chaque question répondue compte (juste ou fausse). Résous-en dans les modes rapide et thèmes.',
  'badge_ht_questions_500': 'Le parcours et les écrans thème offrent beaucoup de questions par session.',
  'badge_ht_questions_1000': 'Combine quêtes quotidiennes et entraînement régulier.',
  'badge_ht_questions_5000': 'Très long terme : joue sur plusieurs âges et thèmes.',
  'badge_ht_streak_5': 'Dans une session, plusieurs bonnes réponses d’affilée sans erreur entre deux.',
  'badge_ht_streak_10': 'Reste concentré ; les bons coups au boss prolongent aussi la série.',
  'badge_ht_streak_25': 'Les sujets difficiles demandent un rythme calme pour la série.',
  'badge_ht_streak_50': 'Commence plus facile, augmente quand la série est stable.',
  'badge_ht_streak_100': 'Meilleure série = plus longue chaîne de bonnes réponses en une session.',
  'badge_ht_fast_10': 'Par question, les secondes sont mesurées. 6–10 s = rapide ; ≤5 s = super rapide (thèmes & rapide).',
  'badge_ht_fast_50': 'Lis vite la question et réponds dès que tu es sûr.',
  'badge_ht_fast_200': 'Beaucoup de bonnes réponses rapides s’accumulent sur les sessions.',
  'badge_ht_superfast_10': 'Vise des réponses en ≤5 s quand le chrono le permet.',
  'badge_ht_perfect_1': 'Termine une session sans mauvaise réponse et avec au moins une question répondue.',
  'badge_ht_perfect_5': 'Répète des sessions parfaites (aucune erreur sur ce run).',
  'badge_ht_perfect_20': 'Parfait = aucune erreur avant la fin (les vies peuvent changer autrement selon les modes).',
  'badge_ht_perfect_50': 'Les parties parfaites progressent lentement ; un mode plus facile aide.',
  'badge_ht_first_friend': 'Dans Amis, ajoute quelqu’un ou accepte une invitation.',
  'badge_ht_friends_5': 'Ajoute plus d’amis dans l’app pour faire monter cette stat.',
  'badge_ht_friends_20': 'Connecte-toi avec des camarades ou la famille.',
  'badge_ht_days_7': 'Au moins une session terminée sur des jours civils consécutifs ; le même jour ne compte qu’une fois.',
  'badge_ht_days_30': 'De courtes sessions quotidiennes gardent la série calendrier.',
  'badge_ht_days_100': 'Badge de fidélité très long terme.',
  'badge_ht_score_1000': 'Les points de session (bonnes réponses, etc.) s’ajoutent au total.',
  'badge_ht_score_10000': 'Combine points des thèmes, du boss et du mode rapide.',
  'badge_ht_score_100000': 'Vise des scores élevés dans tous les modes.',
};

const Map<String, String> _arHowTo = {
  'badge_how_title': 'كيف تكسبه',
  'badge_ht_first_game': 'من الشاشة الرئيسية، أنهِ جلسة في الرياضيات السريعة أو المسارات أو صحيح/خطأ أو زعيم حتى شاشة النتائج.',
  'badge_ht_games_10': 'كل جلسة مكتملة تُحسب مرة واحدة. العب هذه الأوضاع بانتظام.',
  'badge_ht_games_50': 'واصل إنهاء الألعاب؛ المجموع يتراكم في كل الأوضاع.',
  'badge_ht_games_100': 'ممارسة المواضيع والجلسات القصيرة ترفع العدد مع الوقت.',
  'badge_ht_games_500': 'هدف طويل المدى: امزج السريع والمواضيع وزعيم.',
  'badge_ht_questions_100': 'كل سؤال مجاب يُحسب (صحيح أو خطأ). حل في السريع وألعاب المواضيع.',
  'badge_ht_questions_500': 'مسار التعلم وشاشات المواضيع تعطي أسئلة كثيرة لكل جلسة.',
  'badge_ht_questions_1000': 'اجمع المهام اليومية مع التدرب بانتظام.',
  'badge_ht_questions_5000': 'طويل جداً: العب عبر الأعمار والمواضيع.',
  'badge_ht_streak_5': 'في جلسة واحدة، عدة إجابات صحيحة متتالية دون خطأ بينها.',
  'badge_ht_streak_10': 'ركز؛ الإصابات الصحيحة في الزعيم تمد السلسلة أيضاً.',
  'badge_ht_streak_25': 'المواضيع الصعبة تحتاج هدوءاً للحفاظ على السلسلة.',
  'badge_ht_streak_50': 'ابدأ أسهل وزد الصعوبة عند استقرار السلسلة.',
  'badge_ht_streak_100': 'أفضل سلسلة = أطول سلسلة صحيح في جلسة واحدة.',
  'badge_ht_fast_10': 'لكل سؤال تُحسب الثواني. 6–10 ث = سريع؛ ≤5 ث = فائق السرعة (مواضيع وسريع).',
  'badge_ht_fast_50': 'اقرأ السؤال بسرعة وأجب عندما تتأكد.',
  'badge_ht_fast_200': 'كثير من الإجابات السريعة الصحيحة تتراكم بين الجلسات.',
  'badge_ht_superfast_10': 'استهدف الإجابة خلال 5 ثوانٍ عندما يسمح المؤقت.',
  'badge_ht_perfect_1': 'أنهِ جلسة بلا إجابات خاطئة ومع إجابة واحدة على الأقل.',
  'badge_ht_perfect_5': 'كرر جلسات مثالية (بلا أخطاء في تلك الجولة).',
  'badge_ht_perfect_20': 'مثالي = بلا أخطاء حتى نهاية الجلسة (قد تُفقد الأرواح بطرق أخرى في بعض الأوضاع).',
  'badge_ht_perfect_50': 'الألعاب المثالية تتجمع ببطء؛ الإعدادات الأسهل تساعد.',
  'badge_ht_first_friend': 'من شاشة الأصدقاء أضف شخصاً أو اقبل دعوة.',
  'badge_ht_friends_5': 'أضف المزيد من الأصدقاء في التطبيق لرفع هذا الرقم.',
  'badge_ht_friends_20': 'تواصل مع الزملاء أو حسابات العائلة.',
  'badge_ht_days_7': 'جلسة مكتملة واحدة على الأقل في أيام تقويم متتالية؛ نفس اليوم يُحسب يوماً واحداً.',
  'badge_ht_days_30': 'جلسات يومية قصيرة تحافظ على سلسلة التقويم.',
  'badge_ht_days_100': 'وسام ولاء طويل جداً.',
  'badge_ht_score_1000': 'نقاط الجلسات (إجابات صحيحة، إلخ) تُضاف إلى مجموعك.',
  'badge_ht_score_10000': 'اجمع نقاط المواضيع والزعيم والسريع.',
  'badge_ht_score_100000': 'اسعَ لجولات عالية النقاط في كل الأوضاع.',
};

const Map<String, String> _faHowTo = {
  'badge_how_title': 'چطور به دست بیاوری',
  'badge_ht_first_game': 'از خانه، یک دور ریاضی سریع، مسیر موضوع، درست/نادرست یا نبرد رئیس را تا صفحه نتیجه تمام کن.',
  'badge_ht_games_10': 'هر جلسه تمام‌شده یک‌بار شمرده می‌شود. این حالت‌ها را منظم بازی کن.',
  'badge_ht_games_50': 'به بازی ادامه بده؛ مجموع در همه حالت‌ها جمع می‌شود.',
  'badge_ht_games_100': 'تمرین موضوع و جلسه‌های کوتاه با زمان شمارنده را بالا می‌برد.',
  'badge_ht_games_500': 'هدف بلندمدت: ریاضی سریع، موضوعات و رئیس را ترکیب کن.',
  'badge_ht_questions_100': 'هر سؤال جواب‌داده‌شده (درست یا غلط) شمرده می‌شود. در سریع و موضوع حل کن.',
  'badge_ht_questions_500': 'مسیر یادگیری و صفحه موضوع در هر جلسه سؤال زیاد می‌دهد.',
  'badge_ht_questions_1000': 'کارهای روزانه را با تمرین منظم ترکیب کن.',
  'badge_ht_questions_5000': 'خیلی بلندمدت: در سنین و موضوعات مختلف بازی کن.',
  'badge_ht_streak_5': 'در یک جلسه چند پاسخ درست پشت‌سرهم بدون غلط بین آن‌ها.',
  'badge_ht_streak_10': 'تمرکز کن؛ ضربه‌های درست رئیس هم زنجیره را طولانی می‌کند.',
  'badge_ht_streak_25': 'موضوعات سخت برای حفظ زنجیره به آرامش نیاز دارند.',
  'badge_ht_streak_50': 'از آسان شروع کن و وقتی زنجیره پایدار شد سخت‌تر کن.',
  'badge_ht_streak_100': 'بهترین زنجیره = طولانی‌ترین زنجیره درست در یک جلسه.',
  'badge_ht_fast_10': 'برای هر سؤال ثانیه شماری می‌شود. ۶–۱۰ ثانیه = سریع؛ ≤۵ ثانیه = فوق‌سریع (موضوع و سریع).',
  'badge_ht_fast_50': 'سؤال را سریع بخوان و به‌محض اطمینان جواب بده.',
  'badge_ht_fast_200': 'جواب‌های سریع درست زیاد بین جلسات جمع می‌شود.',
  'badge_ht_superfast_10': 'وقتی زمان اجازه می‌دهد در ≤۵ ثانیه جواب بده.',
  'badge_ht_perfect_1': 'یک جلسه را بدون غلط و با حداقل یک سؤال پاسخ‌داده تمام کن.',
  'badge_ht_perfect_5': 'جلسه‌های بی‌نقص را تکرار کن (بدون غلط در همان دور).',
  'badge_ht_perfect_20': 'بی‌نقص یعنی تا پایان جلسه غلط نباشد (در بعضی حالت‌ها جان‌ها جور دیگر از دست می‌روند).',
  'badge_ht_perfect_50': 'بازی‌های بی‌نقص آهسته جمع می‌شوند؛ حالت آسان‌تر کمک می‌کند.',
  'badge_ht_first_friend': 'از صفحه دوستان کسی را اضافه کن یا دعوت را بپذیر.',
  'badge_ht_friends_5': 'دوستان بیشتری در برنامه اضافه کن تا این آمار بالا برود.',
  'badge_ht_friends_20': 'با هم‌کلاسی‌ها یا خانواده وصل شو.',
  'badge_ht_days_7': 'حداقل یک جلسه تمام در روزهای تقویمی پشت‌سرهم؛ همان روز فقط یک‌بار شمرده می‌شود.',
  'badge_ht_days_30': 'جلسه‌های کوتاه روزانه زنجیره تقویم را نگه می‌دارد.',
  'badge_ht_days_100': 'نشان وفاداری خیلی بلندمدت.',
  'badge_ht_score_1000': 'امتیاز جلسات (پاسخ درست و غیره) به مجموع تو اضافه می‌شود.',
  'badge_ht_score_10000': 'امتیاز موضوع، رئیس و ریاضی سریع را ترکیب کن.',
  'badge_ht_score_100000': 'در همه حالت‌ها به دورهای پرامتیاز فکر کن.',
};

const Map<String, String> _zhHowTo = {
  'badge_how_title': '如何获得',
  'badge_ht_first_game': '从首页完成一次快速数学、主题路径、是非或首领战，直到结果界面。',
  'badge_ht_games_10': '每完成一局计一次。经常玩这些模式。',
  'badge_ht_games_50': '持续完成游戏；总数在所有模式中累加。',
  'badge_ht_games_100': '主题练习与短局会逐步提高次数。',
  'badge_ht_games_500': '长期目标：混合快速数学、主题与首领。',
  'badge_ht_questions_100': '每个作答的问题都计数（对错都算）。在快速与主题中解题。',
  'badge_ht_questions_500': '学习路线与主题界面每局有很多题目。',
  'badge_ht_questions_1000': '把每日任务与规律练习结合。',
  'badge_ht_questions_5000': '超长期：跨年龄与主题游玩。',
  'badge_ht_streak_5': '一局内连续答对多题，中间无错误。',
  'badge_ht_streak_10': '保持专注；首领中的正确命中也延长连击。',
  'badge_ht_streak_25': '难题需要稳定节奏保住连击。',
  'badge_ht_streak_50': '从简单开始，连击稳定后再提高难度。',
  'badge_ht_streak_100': '最佳连击=单局中最长的正确链条。',
  'badge_ht_fast_10': '每题记录用时。6–10 秒算快；≤5 秒算超快（主题与快速）。',
  'badge_ht_fast_50': '快速读题，确定后立即作答。',
  'badge_ht_fast_200': '多局内大量快速正确作答会累加。',
  'badge_ht_superfast_10': '在计时允许时争取 5 秒内作答。',
  'badge_ht_perfect_1': '一局内零错误且至少回答一题。',
  'badge_ht_perfect_5': '重复完美局（该局无错误）。',
  'badge_ht_perfect_20': '完美指结束前无错误（某些模式生命可能以别的方式失去）。',
  'badge_ht_perfect_50': '完美局积累较慢；较易设置有助于练习。',
  'badge_ht_first_friend': '在好友界面添加或接受邀请。',
  'badge_ht_friends_5': '在应用中添加更多好友以提升此项。',
  'badge_ht_friends_20': '与同学或家庭账号连接。',
  'badge_ht_days_7': '连续公历日每天至少完成一局；同日多次仍计一天。',
  'badge_ht_days_30': '短每日对局有助于保持日历连签。',
  'badge_ht_days_100': '超长期忠诚徽章。',
  'badge_ht_score_1000': '对局得分（正确等）累加到总分。',
  'badge_ht_score_10000': '合并主题、首领与快速数学的得分。',
  'badge_ht_score_100000': '在各模式追求高分回合。',
};

const Map<String, String> _idHowTo = {
  'badge_how_title': 'Cara mendapatkannya',
  'badge_ht_first_game': 'Dari beranda, selesaikan sesi Matematika Cepat, Topik (alur), Benar/Salah, atau Bos sampai layar hasil.',
  'badge_ht_games_10': 'Setiap sesi selesai dihitung sekali. Main mode ini secara rutin.',
  'badge_ht_games_50': 'Terus menyelesaikan permainan; total bertambah di semua mode.',
  'badge_ht_games_100': 'Latihan topik dan sesi pendek menaikkan angka seiring waktu.',
  'badge_ht_games_500': 'Jangka panjang: campur cepat, topik, dan bos.',
  'badge_ht_questions_100': 'Setiap pertanyaan terjawab dihitung (benar/salah). Selesaikan di cepat & topik.',
  'badge_ht_questions_500': 'Perjalanan belajar dan layar topik memberi banyak soal per sesi.',
  'badge_ht_questions_1000': 'Gabung tugas harian dengan latihan rutin.',
  'badge_ht_questions_5000': 'Sangat panjang: main di berbagai usia dan topik.',
  'badge_ht_streak_5': 'Dalam satu sesi, beberapa benar berturut-tanpa salah di antaranya.',
  'badge_ht_streak_10': 'Tetap fokus; pukulan benar di bos juga memperpanjang rangkaian.',
  'badge_ht_streak_25': 'Topik sulit butuh tempo tenang untuk rangkaian.',
  'badge_ht_streak_50': 'Mulai lebih mudah, naikkan saat rangkaian stabil.',
  'badge_ht_streak_100': 'Rangkaian terbaik = rantai benar terpanjang dalam satu sesi.',
  'badge_ht_fast_10': 'Per soal detik dicatat. 6–10 dtk = cepat; ≤5 dtk = super cepat (topik & cepat).',
  'badge_ht_fast_50': 'Baca cepat dan jawab setelah yakin.',
  'badge_ht_fast_200': 'Banyak jawaban cepat benar terakumulasi antar sesi.',
  'badge_ht_superfast_10': 'Target jawab ≤5 dtk bila timer mengizinkan.',
  'badge_ht_perfect_1': 'Selesaikan sesi tanpa jawaban salah dan minimal satu soal terjawab.',
  'badge_ht_perfect_5': 'Ulangi sesi sempurna (tanpa salah di putaran itu).',
  'badge_ht_perfect_20': 'Sempurna = tanpa salah sampai akhir (nyawa bisa hilang lain di beberapa mode).',
  'badge_ht_perfect_50': 'Permainan sempurna terkumpul lambat; pengaturan lebih mudah membantu.',
  'badge_ht_first_friend': 'Di Teman, tambah seseorang atau terima undangan.',
  'badge_ht_friends_5': 'Tambah lebih banyak teman di app untuk stat ini.',
  'badge_ht_friends_20': 'Terhubung dengan teman sekelas atau keluarga.',
  'badge_ht_days_7': 'Minimal satu sesi selesai pada hari kalender berturut-turut; hari yang sama tetap satu hari.',
  'badge_ht_days_30': 'Sesi pendek harian menjaga streak kalender.',
  'badge_ht_days_100': 'Lencana loyalitas sangat jangka panjang.',
  'badge_ht_score_1000': 'Poin dari sesi (jawaban benar, dll.) menambah skor total.',
  'badge_ht_score_10000': 'Gabungkan poin topik, bos, dan cepat.',
  'badge_ht_score_100000': 'Kejar putaran bernilai tinggi di semua mode.',
};

const Map<String, String> _kuHowTo = {
  'badge_how_title': 'Çawa bi dest bixe',
  'badge_ht_first_game': 'Ji malê, danişînekê di Matematîka Zû, Rêça mijaran, Rast/Nerast an şerê Boss de heta dîmêra encaman qed bike.',
  'badge_ht_games_10': 'Her danişîna qediyayî carekê tê hesibandin. Bi domdarî van modan bilîze.',
  'badge_ht_games_50': 'Lîstikan bidomîne; kom di hemû modan de zêde dibe.',
  'badge_ht_games_100': 'Pratîka mijaran û danişînên kurt hejmarê bi demê re bilind dikin.',
  'badge_ht_games_500': 'Armanca dirêj: zû, mijar û boss tevlihev bike.',
  'badge_ht_questions_100': 'Her pirsên bersivdayî (rast an xelet) tên hesibandin. Di zû û mijaran de çareser bike.',
  'badge_ht_questions_500': 'Rêya fêrbûnê û dîmênên mijaran pir pirs di her danişînê de didin.',
  'badge_ht_questions_1000': 'Karên rojane bi pratîka birêkûpêk re bike yek.',
  'badge_ht_questions_5000': 'Pir dirêj: li temen û mijaran bilîze.',
  'badge_ht_streak_5': 'Di danişînekê de çend rast li pey hev bê xeletî di navberê de.',
  'badge_ht_streak_10': 'Bisekin; rastên boss jî zincîrê dirêj dikin.',
  'badge_ht_streak_25': 'Mijarên dijwar ji bo zincîrê aramtî pêwîst dikin.',
  'badge_ht_streak_50': 'Ji hêsan dest pê bike, gava zincîr stabîl be zehmetiyê zêde bike.',
  'badge_ht_streak_100': 'Baştirîn zincîr = dirêjtirîn zincîra rast di danişînekê de.',
  'badge_ht_fast_10': 'Ji bo her pirsî saniye tên pîvan. 6–10 s = zû; ≤5 s = pir-zû (mijar û zû).',
  'badge_ht_fast_50': 'Zû bixwîne û dema bawer bî bersiv bide.',
  'badge_ht_fast_200': 'Bersivên zû yên rast di navbera danişînan de kom dibin.',
  'badge_ht_superfast_10': 'Armanc ≤5 s dema demjimêr destûrê bide.',
  'badge_ht_perfect_1': 'Danişînekê bê bersiva xelet û bi kêmanî yek pirsî qed bike.',
  'badge_ht_perfect_5': 'Danişînên bêkêmasî dubare bike (bê xeletî di wê gerê de).',
  'badge_ht_perfect_20': 'Bêkêmasî = heta dawîyê bê xeletî (di hin modan de jiyan dikare cuda winda bibe).',
  'badge_ht_perfect_50': 'Lîstikên bêkêmasî bi hêdî kom dibin; mîhengên hêsantir alîkar in.',
  'badge_ht_first_friend': 'Di Hevalan de kesekê lê zêde bike an vexwendinê qebûl bike.',
  'badge_ht_friends_5': 'Zêdetir heval di sepanê de lê zêde bike.',
  'badge_ht_friends_20': 'Bi hevserok an malbatê ve girê bide.',
  'badge_ht_days_7': 'Her rojekê kêmanî danişînekê qediyayî li rojên peywendîdar; heman roj carekê tê hesibandin.',
  'badge_ht_days_30': 'Danişînên kurt ên rojane zincîra salnameyê digirin.',
  'badge_ht_days_100': 'Nîşana sadakatê ya pir-dirêj.',
  'badge_ht_score_1000': 'Pûanên ji danişînan (bersivên rast, hwd.) tevlî kom dibin.',
  'badge_ht_score_10000': 'Pûanên mijar, boss û zû tevlihev bike.',
  'badge_ht_score_100000': 'Di hemû modan de lîstikên bi pûanên bilind armanc bike.',
};

const Map<String, String> _ruHowTo = {
  'badge_how_title': 'Как получить',
  'badge_ht_first_game': 'С главного экрана завершите сессию «Быстрая математика», «Темы», «Верно/неверно» или «Босс» до экрана результатов.',
  'badge_ht_games_10': 'Каждая завершённая сессия считается один раз. Регулярно играйте в эти режимы.',
  'badge_ht_games_50': 'Продолжайте завершать игры; сумма растёт во всех режимах.',
  'badge_ht_games_100': 'Практика по темам и короткие сессии со временем увеличивают счётчик.',
  'badge_ht_games_500': 'Долгая цель: чередуйте быстрый режим, темы и босса.',
  'badge_ht_questions_100': 'Считается каждый ответ (верный или неверный). Решайте в быстром режиме и темах.',
  'badge_ht_questions_500': 'Путь обучения и экраны тем дают много вопросов за сессию.',
  'badge_ht_questions_1000': 'Сочетайте ежедневные задания с регулярной практикой.',
  'badge_ht_questions_5000': 'Очень долгосрочно: играйте в разных возрастах и темах.',
  'badge_ht_streak_5': 'В одной сессии несколько правильных подряд без ошибки между ними.',
  'badge_ht_streak_10': 'Держите фокус; попадания по боссу тоже удлиняют серию.',
  'badge_ht_streak_25': 'Сложные темы требуют спокойного темпа для серии.',
  'badge_ht_streak_50': 'Начинайте легче, повышайте сложность, когда серия стабильна.',
  'badge_ht_streak_100': 'Лучшая серия = самая длинная цепочка верных ответов за сессию.',
  'badge_ht_fast_10': 'На каждый вопрос считаются секунды. 6–10 с = быстро; ≤5 с = супербыстро (темы и быстрый).',
  'badge_ht_fast_50': 'Быстро читайте вопрос и отвечайте, когда уверены.',
  'badge_ht_fast_200': 'Много быстрых верных ответов суммируются между сессиями.',
  'badge_ht_superfast_10': 'Старайтесь отвечать за ≤5 с, когда позволяет таймер.',
  'badge_ht_perfect_1': 'Завершите сессию без ошибок и хотя бы с одним ответом.',
  'badge_ht_perfect_5': 'Повторяйте идеальные сессии (без ошибок в этом заходе).',
  'badge_ht_perfect_20': 'Идеально = без ошибок до конца (в некоторых режимах жизни теряются иначе).',
  'badge_ht_perfect_50': 'Идеальные игры накапливаются медленно; лёгкие настройки помогают.',
  'badge_ht_first_friend': 'В «Друзьях» добавьте кого-то или примите приглашение.',
  'badge_ht_friends_5': 'Добавляйте друзей в приложении, чтобы росла эта статистика.',
  'badge_ht_friends_20': 'Свяжитесь с одноклассниками или семейными аккаунтами.',
  'badge_ht_days_7': 'Хотя бы одна завершённая сессия в подряд идущие календарные дни; в тот же день считается один раз.',
  'badge_ht_days_30': 'Короткие ежедневные сессии поддерживают календарную серию.',
  'badge_ht_days_100': 'Очень долгосрочный значок лояльности.',
  'badge_ht_score_1000': 'Очки сессий (правильные ответы и т.д.) суммируются в общий счёт.',
  'badge_ht_score_10000': 'Суммируйте очки тем, босса и быстрого режима.',
  'badge_ht_score_100000': 'Добивайтесь высоких очков во всех режимах.',
};

const Map<String, String> _jaHowTo = {
  'badge_how_title': '獲得方法',
  'badge_ht_first_game': 'ホームからクイック算数・トピック（学習パス）・○×・ボスのいずれかを結果画面まで終える。',
  'badge_ht_games_10': '完了したセッションは1回ずつカウント。これらのモードを定期的にプレイ。',
  'badge_ht_games_50': 'プレイを続けると全モードで合計が増える。',
  'badge_ht_games_100': 'トピック練習と短時間プレイで徐々に増える。',
  'badge_ht_games_500': '長期目標：クイック・トピック・ボスを組み合わせる。',
  'badge_ht_questions_100': '解答した問題はすべてカウント（正誤問わず）。クイックとトピックで解く。',
  'badge_ht_questions_500': '学習パスとトピック画面は1セッションに多くの問題。',
  'badge_ht_questions_1000': 'デイリーと継続練習を組み合わせる。',
  'badge_ht_questions_5000': '超長期：年齢やトピックをまたいでプレイ。',
  'badge_ht_streak_5': '1セッションで間に誤答なしに複数正解。',
  'badge_ht_streak_10': '集中；ボスの正解も連続に含まれる。',
  'badge_ht_streak_25': '難しいトピックは落ち着いたペースで連続を維持。',
  'badge_ht_streak_50': '易しめから始め、安定したら難易度アップ。',
  'badge_ht_streak_100': '最高連続＝1セッションでの最長正解チェーン。',
  'badge_ht_fast_10': '各問題の秒数を計測。6〜10秒＝速い、5秒以下＝超高速（トピック＆クイック）。',
  'badge_ht_fast_50': '素早く読み、確信したらすぐ答える。',
  'badge_ht_fast_200': 'セッションをまたいで速い正解が積み上がる。',
  'badge_ht_superfast_10': 'タイマーが許すなら5秒以内を目指す。',
  'badge_ht_perfect_1': '誤答ゼロで少なくとも1問答えてセッション完了。',
  'badge_ht_perfect_5': '完璧なセッション（その回に誤答なし）を繰り返す。',
  'badge_ht_perfect_20': '完璧＝終了まで誤答なし（モードによってはライフ減り方が異なる）。',
  'badge_ht_perfect_50': '完璧プレイはゆっくり貯まる；易しい設定が練習に有利。',
  'badge_ht_first_friend': 'フレンド画面で追加か招待を承認。',
  'badge_ht_friends_5': 'アプリでもっと友だちを増やす。',
  'badge_ht_friends_20': 'クラスメイトや家族アカウントとつながる。',
  'badge_ht_days_7': '連続する暦日に少なくとも1回完了セッション；同日は1日として数える。',
  'badge_ht_days_30': '短い毎日プレイでカレンダー連続を維持。',
  'badge_ht_days_100': '超長期ロイヤルティバッジ。',
  'badge_ht_score_1000': 'セッションの得点（正解など）が合計に加算。',
  'badge_ht_score_10000': 'トピック・ボス・クイックの得点を合わせる。',
  'badge_ht_score_100000': '全モードで高得点ラウンドを狙う。',
};

const Map<String, String> _koHowTo = {
  'badge_how_title': '획득 방법',
  'badge_ht_first_game': '홈에서 빠른 수학, 주제(학습 경로), 참/거짓 또는 보스 중 하나를 결과 화면까지 완료하세요.',
  'badge_ht_games_10': '완료한 세션은 한 번씩만 집계됩니다. 이 모드를 꾸준히 플레이하세요.',
  'badge_ht_games_50': '게임을 계속 완료하면 모든 모드에서 합계가 쌓입니다.',
  'badge_ht_games_100': '주제 연습과 짧은 세션으로 시간이 지나며 증가합니다.',
  'badge_ht_games_500': '장기 목표: 빠른 수학, 주제, 보스를 섞으세요.',
  'badge_ht_questions_100': '맞든 틀리든 답한 모든 문제가 집계됩니다. 빠른 수학과 주제에서 풀세요.',
  'badge_ht_questions_500': '학습 여정과 주제 화면은 세션당 문제가 많습니다.',
  'badge_ht_questions_1000': '일일 과제와 꾸준한 연습을 함께하세요.',
  'badge_ht_questions_5000': '매우 장기: 여러 나이·주제에서 플레이하세요.',
  'badge_ht_streak_5': '한 세션에서 사이에 오답 없이 연속으로 여러 정답.',
  'badge_ht_streak_10': '집중하세요; 보스의 정답도 연속을 이어 줍니다.',
  'badge_ht_streak_25': '어려운 주제는 연속을 위해 차분한 속도가 필요합니다.',
  'badge_ht_streak_50': '쉬운 난이도로 시작해 연속이 안정되면 올리세요.',
  'badge_ht_streak_100': '최고 연속 = 한 세션에서 가장 긴 정답 체인.',
  'badge_ht_fast_10': '문제마다 초가 기록됩니다. 6–10초=빠름; 5초 이하=초고속(주제·빠른 수학).',
  'badge_ht_fast_50': '빠르게 읽고 확신하면 바로 답하세요.',
  'badge_ht_fast_200': '세션 간에 빠른 정답이 많이 쌓입니다.',
  'badge_ht_superfast_10': '타이머가 허용하면 5초 안에 답하세요.',
  'badge_ht_perfect_1': '오답 없이 최소 한 문제를 풀고 세션을 끝내세요.',
  'badge_ht_perfect_5': '완벽한 세션(그 판에 오답 없음)을 반복하세요.',
  'badge_ht_perfect_20': '완벽=세션 끝까지 오답 없음(일부 모드에서는 목숨이 다르게 줄 수 있음).',
  'badge_ht_perfect_50': '완벽 게임은 천천히 쌓입니다; 쉬운 설정이 연습에 도움.',
  'badge_ht_first_friend': '친구 화면에서 추가하거나 초대를 수락하세요.',
  'badge_ht_friends_5': '앱에서 친구를 더 많이 추가하세요.',
  'badge_ht_friends_20': '급우나 가족 계정과 연결하세요.',
  'badge_ht_days_7': '연속된 달력 날짜마다 최소 한 번 완료 세션; 같은 날 여러 번은 하루로 칩니다.',
  'badge_ht_days_30': '짧은 일일 세션이 달력 연속을 유지합니다.',
  'badge_ht_days_100': '매우 장기 충성 배지.',
  'badge_ht_score_1000': '세션 점수(정답 등)가 총점에 더해집니다.',
  'badge_ht_score_10000': '주제, 보스, 빠른 수학 점수를 합치세요.',
  'badge_ht_score_100000': '모든 모드에서 고득점 라운드를 노리세요.',
};

const Map<String, String> _hiHowTo = {
  'badge_how_title': 'कैसे अर्जित करें',
  'badge_ht_first_game': 'होम से त्वरित गणित, विषय (पथ), सही/गलत या बॉस में से कोई सत्र परिणाम स्क्रीन तक पूरा करें।',
  'badge_ht_games_10': 'हर पूरा सत्र एक बार गिना जाता है। इन मोड को नियमित खेलें।',
  'badge_ht_games_50': 'खेलते रहें; योग सभी मोड में जुड़ता है।',
  'badge_ht_games_100': 'विषय अभ्यास और छोटे सत्र समय के साथ संख्या बढ़ाते हैं।',
  'badge_ht_games_500': 'दीर्घकालिक: त्वरित, विषय और बॉस मिलाएँ।',
  'badge_ht_questions_100': 'हर उत्तर दिया प्रश्न गिना जाता है (सही या गलत)। त्वरित और विषय में हल करें।',
  'badge_ht_questions_500': 'सीखने का रास्ता और विषय स्क्रीन प्रति सत्र कई प्रश्न देती हैं।',
  'badge_ht_questions_1000': 'दैनिक कार्यों के साथ नियमित अभ्यास जोड़ें।',
  'badge_ht_questions_5000': 'बहुत दीर्घकालिक: उम्र और विषयों में खेलें।',
  'badge_ht_streak_5': 'एक सत्र में बिना बीच गलत के कई सही लगातार।',
  'badge_ht_streak_10': 'ध्यान दें; बॉस में सही प्रहार भी श्रृंखला बढ़ाते हैं।',
  'badge_ht_streak_25': 'कठिन विषयों के लिए श्रृंखला के लिए शांत गति चाहिए।',
  'badge_ht_streak_50': 'आसान से शुरू करें, श्रृंखला स्थिर होने पर कठिनाई बढ़ाएँ।',
  'badge_ht_streak_100': 'सर्वश्रेष्ठ श्रृंखला = एक सत्र में सबसे लंबी सही श्रृंखला।',
  'badge_ht_fast_10': 'प्रति प्रश्न सेकंड मापे जाते हैं। 6–10 से = तेज़; ≤5 से = अति-तेज़ (विषय और त्वरित)।',
  'badge_ht_fast_50': 'जल्दी पढ़ें और जब निश्चित हों तब उत्तर दें।',
  'badge_ht_fast_200': 'सत्रों में कई तेज़ सही उत्तर जुड़ते हैं।',
  'badge_ht_superfast_10': 'टाइमर अनुमति दे तो 5 सेकंड में उत्तर दें।',
  'badge_ht_perfect_1': 'बिना गलत उत्तर और कम से कम एक प्रश्न के साथ सत्र पूरा करें।',
  'badge_ht_perfect_5': 'पूर्ण सत्र दोहराएँ (उस रन में कोई गलत नहीं)।',
  'badge_ht_perfect_20': 'पूर्ण = अंत तक कोई गलत नहीं (कुछ मोड में जान अलग तरह घट सकती है)।',
  'badge_ht_perfect_50': 'पूर्ण खेल धीरे जमा होते हैं; आसान सेटिंग मदद करती है।',
  'badge_ht_first_friend': 'मित्र स्क्रीन से किसी को जोड़ें या निमंत्रण स्वीकार करें।',
  'badge_ht_friends_5': 'ऐप में और मित्र जोड़ें।',
  'badge_ht_friends_20': 'सहपाठी या परिवार खातों से जुड़ें।',
  'badge_ht_days_7': 'लगातार कैलेंडर दिनों पर कम से कम एक पूरा सत्र; उसी दिन अतिरिक्त एक दिन गिना जाता है।',
  'badge_ht_days_30': 'छोटे दैनिक सत्र कैलेंडर श्रृंखला रखते हैं।',
  'badge_ht_days_100': 'बहुत दीर्घकालिक निष्ठा बैज।',
  'badge_ht_score_1000': 'सत्र अंक (सही उत्तर आदि) कुल में जुड़ते हैं।',
  'badge_ht_score_10000': 'विषय, बॉस और त्वरित अंक मिलाएँ।',
  'badge_ht_score_100000': 'सभी मोड में उच्च-स्कोर राउंड लक्ष्य करें।',
};

const Map<String, String> _urHowTo = {
  'badge_how_title': 'کیسے حاصل کریں',
  'badge_ht_first_game': 'ہوم سے فوری ریاضی، موضوع (راستہ)، صحیح/غلط یا باس میں سے کوئی سیشن نتائج کی سکرین تک مکمل کریں۔',
  'badge_ht_games_10': 'ہر مکمل سیشن ایک بار گنا جاتا ہے۔ ان موڈز کو باقاعدگی سے کھیلیں۔',
  'badge_ht_games_50': 'کھیلتے رہیں؛ کل تمام موڈز میں جمع ہوتا ہے۔',
  'badge_ht_games_100': 'موضوع کی مشق اور مختصر سیشن وقت کے ساتھ شمار بڑھاتے ہیں۔',
  'badge_ht_games_500': 'طویل مدت: فوری، موضوع اور باس ملا کر کھیلیں۔',
  'badge_ht_questions_100': 'ہر جواب دیا گیا سوال گنا جاتا ہے (صحیح یا غلط)۔ فوری اور موضوع میں حل کریں۔',
  'badge_ht_questions_500': 'سیکھنے کا سفر اور موضوع کی اسکرینیں فی سیشن بہت سے سوالات دیتی ہیں۔',
  'badge_ht_questions_1000': 'روزانہ کاموں کے ساتھ باقاعدہ مشق ملائیں۔',
  'badge_ht_questions_5000': 'بہت طویل مدت: عمر اور موضوعات میں کھیلیں۔',
  'badge_ht_streak_5': 'ایک سیشن میں درمیان میں غلطی کے بغیر متواتر کئی صحیح۔',
  'badge_ht_streak_10': 'توجہ مرکوز رکھیں؛ باس میں صحیح ضربیں بھی سلسلہ بڑھاتی ہیں۔',
  'badge_ht_streak_25': 'مشکل موضوعات کے لیے سلسلے کے لیے پرسکون رفتار درکار ہے۔',
  'badge_ht_streak_50': 'آسان سے شروع کریں، سلسلہ مستحکم ہو تو مشکل بڑھائیں۔',
  'badge_ht_streak_100': 'بہترین سلسلہ = ایک سیشن میں سب سے لمبا صحیح سلسلہ۔',
  'badge_ht_fast_10': 'فی سوال سیکنڈ شمار ہوتے ہیں۔ 6–10 س = تیز؛ ≤5 س = انتہائی تیز (موضوع اور فوری)۔',
  'badge_ht_fast_50': 'جلدی پڑھیں اور جب یقین ہو تب جواب دیں۔',
  'badge_ht_fast_200': 'سیشنز کے درمیان بہت سے تیز صحیح جواب جمع ہوتے ہیں۔',
  'badge_ht_superfast_10': 'ٹائمر اجازت دے تو 5 سیکنڈ میں جواب دیں۔',
  'badge_ht_perfect_1': 'بغیر غلط جواب اور کم از کم ایک سوال کے ساتھ سیشن مکمل کریں۔',
  'badge_ht_perfect_5': 'کامل سیشن دہرائیں (اس رن میں کوئی غلط نہیں)۔',
  'badge_ht_perfect_20': 'کامل = اختتام تک کوئی غلط نہیں (کچھ موڈز میں جانیں اور طرح کم ہو سکتی ہیں)۔',
  'badge_ht_perfect_50': 'کامل کھیل آہستہ جمع ہوتے ہیں؛ آسان ترتیب مدد کرتی ہے۔',
  'badge_ht_first_friend': 'دوستوں کی سکرین سے کسی کو شامل کریں یا دعوت قبول کریں۔',
  'badge_ht_friends_5': 'ایپ میں مزید دوست شامل کریں۔',
  'badge_ht_friends_20': 'کلاس کے ساتھیوں یا خاندانی اکاؤنٹس سے جڑیں۔',
  'badge_ht_days_7': 'مسلسل کیلنڈر دنوں پر کم از کم ایک مکمل سیشن؛ ایک ہی دن اضافی ایک دن شمار ہوتا ہے۔',
  'badge_ht_days_30': 'مختصر روزانہ سیشن کیلنڈر سلسلہ رکھتے ہیں۔',
  'badge_ht_days_100': 'بہت طویل وفاداری بیج۔',
  'badge_ht_score_1000': 'سیشن کے اسکور (صحیح وغیرہ) کل میں شامل ہوتے ہیں۔',
  'badge_ht_score_10000': 'موضوع، باس اور فوری اسکور ملا کر۔',
  'badge_ht_score_100000': 'تمام موڈز میں اعلیٰ اسکور راؤنڈز کا ہدف رکھیں۔',
};

const Map<String, String> _ptHowTo = {
  'badge_how_title': 'Como ganhar',
  'badge_ht_first_game': 'Na inicial, termine uma sessão de Matemática rápida, Tópicos (trilha), Verdadeiro/Falso ou Chefe até o ecrã de resultados.',
  'badge_ht_games_10': 'Cada sessão concluída conta uma vez. Jogue estes modos regularmente.',
  'badge_ht_games_50': 'Continue a terminar jogos; o total soma em todos os modos.',
  'badge_ht_games_100': 'Prática por tópicos e sessões curtas aumentam a contagem.',
  'badge_ht_games_500': 'Longo prazo: misture rápido, tópicos e chefe.',
  'badge_ht_questions_100': 'Cada pergunta respondida conta (certa ou errada). Resolva no rápido e nos tópicos.',
  'badge_ht_questions_500': 'A jornada de aprendizagem e os tópicos dão muitas perguntas por sessão.',
  'badge_ht_questions_1000': 'Combine tarefas diárias com prática regular.',
  'badge_ht_questions_5000': 'Muito longo prazo: jogue em várias idades e tópicos.',
  'badge_ht_streak_5': 'Numa sessão, várias certas seguidas sem erro entre elas.',
  'badge_ht_streak_10': 'Mantenha foco; acertos no chefe também prolongam a sequência.',
  'badge_ht_streak_25': 'Tópicos difíceis precisam de ritmo calmo para a sequência.',
  'badge_ht_streak_50': 'Comece mais fácil e aumente quando a sequência for estável.',
  'badge_ht_streak_100': 'Melhor sequência = maior cadeia de certas numa sessão.',
  'badge_ht_fast_10': 'Por pergunta mede-se o tempo. 6–10 s = rápida; ≤5 s = super-rápida (tópicos e rápido).',
  'badge_ht_fast_50': 'Leia depressa e responda quando tiver a certeza.',
  'badge_ht_fast_200': 'Muitas respostas rápidas certas acumulam entre sessões.',
  'badge_ht_superfast_10': 'Vise respostas em ≤5 s quando o temporizador permitir.',
  'badge_ht_perfect_1': 'Termine uma sessão sem errados e com pelo menos uma pergunta respondida.',
  'badge_ht_perfect_5': 'Repita sessões perfeitas (sem errados nessa volta).',
  'badge_ht_perfect_20': 'Perfeito = sem errados até ao fim (vidas podem mudar de outra forma nalguns modos).',
  'badge_ht_perfect_50': 'Jogos perfeitos acumulam devagar; definições mais fáceis ajudam.',
  'badge_ht_first_friend': 'Em Amigos, adicione alguém ou aceite um convite.',
  'badge_ht_friends_5': 'Adicione mais amigos na app para esta estatística.',
  'badge_ht_friends_20': 'Ligue-se a colegas ou contas de família.',
  'badge_ht_days_7': 'Pelo menos uma sessão concluída em dias de calendário consecutivos; no mesmo dia conta um dia.',
  'badge_ht_days_30': 'Sessões curtas diárias mantêm a sequência do calendário.',
  'badge_ht_days_100': 'Distintivo de lealdade de muito longo prazo.',
  'badge_ht_score_1000': 'Pontos das sessões (certas, etc.) somam ao total.',
  'badge_ht_score_10000': 'Combine pontos de tópicos, chefe e rápido.',
  'badge_ht_score_100000': 'Procure rodadas de pontuação alta em todos os modos.',
};

const Map<String, String> _itHowTo = {
  'badge_how_title': 'Come ottenerlo',
  'badge_ht_first_game': 'Dalla home completa una sessione Matematica veloce, Percorsi, Vero/Falso o Boss fino alla schermata risultati.',
  'badge_ht_games_10': 'Ogni sessione completata vale una volta. Gioca regolarmente a queste modalità.',
  'badge_ht_games_50': 'Continua a finire partite; il totale cresce in tutte le modalità.',
  'badge_ht_games_100': 'Pratica sui temi e sessioni brevi aumentano il conteggio.',
  'badge_ht_games_500': 'Lungo termine: alterna veloce, temi e boss.',
  'badge_ht_questions_100': 'Ogni domanda risposta conta (giusta o sbagliata). Risolvi in veloce e temi.',
  'badge_ht_questions_500': 'Il percorso e le schermate tema danno molte domande per sessione.',
  'badge_ht_questions_1000': 'Combina compiti giornalieri ed esercizio regolare.',
  'badge_ht_questions_5000': 'Molto lungo termine: gioca tra età e temi diversi.',
  'badge_ht_streak_5': 'In una sessione, più risposte giuste di fila senza errori in mezzo.',
  'badge_ht_streak_10': 'Resta concentrato; i colpi giusti nel boss allungano la serie.',
  'badge_ht_streak_25': 'Argomenti difficili richiedono ritmo calmo per la serie.',
  'badge_ht_streak_50': 'Inizia più facile, aumenta quando la serie è stabile.',
  'badge_ht_streak_100': 'Migliore serie = catena più lunga di risposte giuste in una sessione.',
  'badge_ht_fast_10': 'Per domanda si misurano i secondi. 6–10 s = veloce; ≤5 s = super-veloce (temi e veloce).',
  'badge_ht_fast_50': 'Leggi velocemente e rispondi appena sei sicuro.',
  'badge_ht_fast_200': 'Molte risposte veloci corrette si sommano tra le sessioni.',
  'badge_ht_superfast_10': 'Punta a rispondere in ≤5 s quando il timer lo consente.',
  'badge_ht_perfect_1': 'Termina una sessione senza errori e con almeno una domanda risposta.',
  'badge_ht_perfect_5': 'Ripeti sessioni perfette (nessun errore in quel run).',
  'badge_ht_perfect_20': 'Perfetto = nessun errore fino alla fine (in alcune modalità le vite cambiano diversamente).',
  'badge_ht_perfect_50': 'Le partite perfette si accumulano lentamente; impostazioni più facili aiutano.',
  'badge_ht_first_friend': 'In Amici aggiungi qualcuno o accetta un invito.',
  'badge_ht_friends_5': 'Aggiungi più amici nell’app per questa statistica.',
  'badge_ht_friends_20': 'Collegati con compagni o account famiglia.',
  'badge_ht_days_7': 'Almeno una sessione completata in giorni di calendario consecutivi; nello stesso giorno vale un giorno.',
  'badge_ht_days_30': 'Sessioni brevi quotidiane mantengono la serie sul calendario.',
  'badge_ht_days_100': 'Distintivo di fedeltà a lunghissimo termine.',
  'badge_ht_score_1000': 'I punti delle sessioni (risposte giuste, ecc.) si sommano al totale.',
  'badge_ht_score_10000': 'Combina punti da temi, boss e veloce.',
  'badge_ht_score_100000': 'Punta a partite ad alto punteggio in tutte le modalità.',
};

const Map<String, String> _plHowTo = {
  'badge_how_title': 'Jak zdobyć',
  'badge_ht_first_game': 'Z ekranu głównego dokończ sesję Szybka matematyka, Tematy (ścieżka), Prawda/Fałsz lub Boss do ekranu wyników.',
  'badge_ht_games_10': 'Każda ukończona sesja liczy się raz. Regularnie graj w te tryby.',
  'badge_ht_games_50': 'Kończ kolejne gry; suma rośnie we wszystkich trybach.',
  'badge_ht_games_100': 'Praktyka tematów i krótkie sesje z czasem zwiększają licznik.',
  'badge_ht_games_500': 'Długoterminowo: mieszaj szybki tryb, tematy i bossa.',
  'badge_ht_questions_100': 'Liczy się każda udzielona odpowiedź (dobra lub zła). Rozwiązuj w szybkim i tematach.',
  'badge_ht_questions_500': 'Ścieżka nauki i ekrany tematów dają wiele pytań na sesję.',
  'badge_ht_questions_1000': 'Łącz codzienne zadania z regularną praktyką.',
  'badge_ht_questions_5000': 'Bardzo długoterminowo: graj w różnych wiekach i tematach.',
  'badge_ht_streak_5': 'W jednej sesji kilka poprawnych z rzędu bez błędu pomiędzy.',
  'badge_ht_streak_10': 'Skupienie; trafienia w bossie też wydłużają serię.',
  'badge_ht_streak_25': 'Trudne tematy wymagają spokojnego tempa dla serii.',
  'badge_ht_streak_50': 'Zacznij łatwiej, zwiększaj, gdy seria jest stabilna.',
  'badge_ht_streak_100': 'Najlepsza seria = najdłuższy łańcuch dobrych odpowiedzi w jednej sesji.',
  'badge_ht_fast_10': 'Na pytanie mierzone są sekundy. 6–10 s = szybko; ≤5 s = superszybko (tematy i szybki).',
  'badge_ht_fast_50': 'Czytaj szybko i odpowiadaj, gdy jesteś pewien.',
  'badge_ht_fast_200': 'Wiele szybkich dobrych odpowiedzi sumuje się między sesjami.',
  'badge_ht_superfast_10': 'Celuj w odpowiedź w ≤5 s, gdy timer pozwala.',
  'badge_ht_perfect_1': 'Ukończ sesję bez złych odpowiedzi i z co najmniej jednym pytaniem.',
  'badge_ht_perfect_5': 'Powtarzaj idealne sesje (bez błędów w tej rundzie).',
  'badge_ht_perfect_20': 'Idealnie = bez błędów do końca (w niektórych trybach życia giną inaczej).',
  'badge_ht_perfect_50': 'Idealne gry narastają wolno; łatwiejsze ustawienia pomagają.',
  'badge_ht_first_friend': 'W Znajomych dodaj kogoś lub zaakceptuj zaproszenie.',
  'badge_ht_friends_5': 'Dodaj więcej znajomych w aplikacji.',
  'badge_ht_friends_20': 'Połącz się z klasą lub kontami rodziny.',
  'badge_ht_days_7': 'Co najmniej jedna ukończona sesja w kolejnych dniach kalendarza; ten sam dzień liczy się raz.',
  'badge_ht_days_30': 'Krótkie codzienne sesje utrzymują passę kalendarzową.',
  'badge_ht_days_100': 'Odznaka lojalności na bardzo długi okres.',
  'badge_ht_score_1000': 'Punkty z sesji (dobre odpowiedzi itd.) dodają się do sumy.',
  'badge_ht_score_10000': 'Łącz punkty z tematów, bossa i szybkiego trybu.',
  'badge_ht_score_100000': 'Celuj w wysokie wyniki we wszystkich trybach.',
};
