name: mathfunapp
description: "Matematik Macerası - Çocuklar için Matematik Öğrenme Oyunu"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animations: ^2.1.1

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  # Auth
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.3

  # State management
  provider: ^6.1.2

  shared_preferences: ^2.2.2
  
  # Connectivity
  connectivity_plus: ^6.0.3

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
