// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW_-FNmnqqYiduS98djK3fCL3fwLlL7ng',
    appId: '1:728773599076:web:154ca5d8b68dacde6c6471',
    messagingSenderId: '728773599076',
    projectId: 'mathfunapp-1460b',
    authDomain: 'mathfunapp-1460b.firebaseapp.com',
    storageBucket: 'mathfunapp-1460b.firebasestorage.app',
    measurementId: 'G-8YRTYF15LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF4kzyx-S3X6CLtr8lZzZIzvoOERqXXaU',
    appId: '1:728773599076:android:bdd27f3f8529c5f36c6471',
    messagingSenderId: '728773599076',
    projectId: 'mathfunapp-1460b',
    storageBucket: 'mathfunapp-1460b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW_-FNmnqqYiduS98djK3fCL3fwLlL7ng',
    appId: '1:728773599076:web:2f9e1ec223f01a986c6471',
    messagingSenderId: '728773599076',
    projectId: 'mathfunapp-1460b',
    authDomain: 'mathfunapp-1460b.firebaseapp.com',
    storageBucket: 'mathfunapp-1460b.firebasestorage.app',
    measurementId: 'G-9E67HLFLG0',
  );
}
